### ISSUE TITLE
Failed to update plot when it is a Panel layout

### ISSUE THREAD

**Issue by FredRTS** [holoviz/panel#4965]
Hello, 

Thanks you for your great work !

I got an issue with the last panel release 1.0.3, previously running script stops working with  the following exception : AttributeError: 'str' object has no attribute 'param'

This is a simple app where user can select a plot and show it clicking on the button.

It happens with panel version 1.0.3.

The same example is working well with panel 0.14.4

In the example, if 'create_main_plot' return the holoview plot, it works but it return the Column, it fails.

#### ALL software version info

Python version      :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
IPython version     :  8.13.2
Tornado version     :  6.3.2
Bokeh version       :  3.1.1
BokehJS static path :  /opt/conda/envs/env/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.4.0-149-generic-x86_64-with-glibc2.27

Holoviews 1.16.0

#### Description of expected behavior and the observed behavior
Plot must be update when click on the 'create plot' button but an exception is raise

#### Complete, minimal, self-contained example code that reproduces the issue

in sample.py
```

import numpy as np

import panel as pn
import holoviews as hv


hv.extension('bokeh')
pn.extension(loading_spinner='dots', sizing_mode="stretch_width")

N = 200

def create_main_plot(x, y, color):
    data = np.stack([x, y]).T
    title = pn.pane.Markdown(f"# Plot __{color}__")
    pts = hv.Points(data).opts(color=color)

    # return pts  # It works with that return
    return pn.Column(title, pts, sizing_mode='stretch_width')


def app(all_plots):

    select = pn.widgets.Select(name='Select Plot', options=list(
        all_plots.keys()), sizing_mode='stretch_width')

    update_button = pn.widgets.Button(
        name='Create plot', button_type='primary', sizing_mode='stretch_width')

    side_bar = pn.Column(
        select,
        update_button,
        width=200
    )

    @pn.depends(update_button.param.clicks)
    def button_update(_):
        k = select.value

        kwargs = all_plots[k]
        p = create_main_plot(**kwargs)

        return p

    template = pn.template.BootstrapTemplate(title="Super App")

    header = pn.Row("# TEST", sizing_mode='stretch_width')

    template.header.append(header)

    template.sidebar.append(side_bar)
    template.main.append(button_update)

    return template


def starter():
    N = 100

    all_plots = {
        'A': {
            'x': np.random.random(N),
            'y': np.random.random(N),
            'color': 'blue',
        },
        'B': {
            'x': np.random.random(N),
            'y': np.random.random(N),
            'color': 'red',
        },
        'C': {
            'x': np.random.random(N),
            'y': np.random.random(N),
            'color': 'green',
        },
    }

    return app(all_plots)


starter().servable()

```
 then in terminal 
```
panel serve sample.py
```
#### Full traceback

Traceback (most recent call last):
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/reactive.py", line 487, in _server_event
    self._comm_event(doc, event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/reactive.py", line 474, in _comm_event
    state._handle_exception(e)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/io/state.py", line 432, in _handle_exception
    raise exception
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/reactive.py", line 472, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/reactive.py", line 409, in _process_bokeh_event
    self._process_event(event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/widgets/button.py", line 233, in _process_event
    self.clicks += 1
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/param.py", line 827, in _replace_pane
    self._update_inner(new_object)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/pane/base.py", line 700, in _update_inner
    new_pane, internal = self._update_from_object(
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/pane/base.py", line 655, in _update_from_object
    cls._recursive_update(old_object, i, old, new)
  File "/opt/conda/envs/rts/lib/python3.10/site-packages/panel/pane/base.py", line 629, in _recursive_update
    old.param.update(**new_params)
AttributeError: 'str' object has no attribute 'param'

Thank in advance, 

Fred

**Comment by Hoxbro** [comment]
The error you are seeing will be fixed in the next release of Panel.  Though I'm seeing another problem related to collapsing figures, I will open a new issue with it.

**Comment by philippjfr** [comment]
Fixed via https://github.com/holoviz/panel/pull/4958
