### ISSUE TITLE
AttributeError: 'str' object has no attribute 'param'

### ISSUE THREAD

**Issue by apahl** [holoviz/panel#4944]
Hi, I have a web app working with Py 3.9 and Panel 0.14.3 on Ubuntu 22.04.

I just upgraded to Py 3.11 and Panel 1.0.3 and now I get the above error (traceback below). 

The traceback does not point to anywhere in my code, but I could pin it down to the usage of `Column` in the `show_result` function. When I remove the `Column` widget, the error disappears, but then I do not get the desired layout in my app.

Many thanks in advance for your help.

KR Axel

### Minimal example reproducing the error

```Python
import panel as pn
import panel.widgets as pnw

pn.extension()  # sizing_mode="stretch_width")

button = pnw.Button(name="Start Calculation", button_type="primary", disabled=False)


@pn.depends(button)
def show_result(event=None):
    if src.value == "":
        return pn.Column(
            pn.pane.Markdown(
                "Please enter input data.",
                width=600,
            )
        )
    return pn.Column(pn.pane.Markdown("TEST RESULT"))


title = "Minimal Example"

src = pnw.TextAreaInput(name="Input area", max_length=2000, height=400)

app = pn.template.FastListTemplate(
    site="COMAS Datavis",
    title=title,
    theme_toggle=False,
    sidebar=[
        src,
        button,
    ],
    main=[
        show_result,
    ],
    main_layout=None,  # Removes the grey background around the results in the main panel
)

app.servable()

```

#### Stack traceback and/or browser JavaScript console output

```
2023-05-26 12:29:41,167 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1030'}]]}}}]} 
 error: AttributeError("'str' object has no attribute 'param'")
Traceback (most recent call last):
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/reactive.py", line 487, in _server_event
    self._comm_event(doc, event)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/reactive.py", line 474, in _comm_event
    state._handle_exception(e)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/io/state.py", line 432, in _handle_exception
    raise exception
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/reactive.py", line 472, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/reactive.py", line 409, in _process_bokeh_event
    self._process_event(event)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/widgets/button.py", line 232, in _process_event
    self.param.trigger('value')
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/param/parameterized.py", line 1993, in trigger
    self_.set_param(**dict(params, **triggers))
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/param/parameterized.py", line 1929, in set_param
    return self_.update(kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/param.py", line 827, in _replace_pane
    self._update_inner(new_object)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/pane/base.py", line 700, in _update_inner
    new_pane, internal = self._update_from_object(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/pane/base.py", line 655, in _update_from_object
    cls._recursive_update(old_object, i, old, new)
  File "/home/pahl/anaconda3/envs/chem311/lib/python3.11/site-packages/panel/pane/base.py", line 629, in _recursive_update
    old.param.update(**new_params)
    ^^^^^^^^^
AttributeError: 'str' object has no attribute 'param'
```

**Comment by philippjfr** [comment]
Thank you, this is a pretty critical regression. I'll get a fix out in a 1.0.4 release later today.

**Comment by apahl** [comment]
Wow, thanks a lot for the very quick fix.

KR Axel
