### ISSUE TITLE
MyST renderer does not work with Panel 1.2.2

### ISSUE THREAD

**Issue by monodera** [holoviz/panel#5494]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

panel 1.2.2
bokeh 3.2.2
myst-parser 2.0.0
Markdown 3.4.4
markdown-it-py 3.0.0
Python 3.11.5

macOS 13.5.2
Firefox 117.0

##### Expected behavior

Markdown pane is rendered correctly. 

##### Observed behavior

Got following error message.

```
TypeError: MdParserConfig.init() got an unexpected keyword argument 'breaks'

Traceback (most recent call last):
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/Users/monodera/tmp/test_panel/markdown_test.py", line 5, in <module>
    pn.Row(pn.pane.Markdown("# Markdown Text", renderer="myst")).servable()
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/viewable.py", line 392, in servable
    self.server_doc(title=title, location=location) # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/viewable.py", line 1024, in server_doc
    model = self.get_root(doc)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 306, in get_root
    root = super().get_root(doc, comm, preprocess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/viewable.py", line 666, in get_root
    root = self._get_model(doc, comm=comm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 174, in _get_model
    objects, _ = self._get_objects(model, [], doc, root, comm)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 156, in _get_objects
    child = pane._get_model(doc, root, model, comm)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/pane/base.py", line 500, in _get_model
    model = self._bokeh_model(**self._get_properties(doc))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/reactive.py", line 711, in _get_properties
    properties = self._process_param_change(params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/pane/markup.py", line 441, in _process_param_change
    return super()._process_param_change(params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/pane/base.py", line 523, in _process_param_change
    params.update(self._transform_object(params.pop('object')))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/pane/markup.py", line 433, in _transform_object
    html = self._get_parser(
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/tmp/test_panel/.venv/lib/python3.11/site-packages/panel/pane/markup.py", line 396, in _get_parser
    config = MdParserConfig(heading_anchors=1, enable_extensions=[
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MdParserConfig.__init__() got an unexpected keyword argument 'breaks'
```

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

# # The following two lines work.
# pn.Row(pn.pane.Markdown("# Markdown Text", renderer="markdown-it")).servable()
# pn.Row(pn.pane.Markdown("# Markdown Text", renderer="markdown")).servable()

# MyST engine does not work
pn.Row(pn.pane.Markdown("# Markdown Text", renderer="myst")).servable()
```

**Comment by ahuang11** [comment]
Thanks for reporting this issue!

Would you be interested in contributing a fix?

I think it's a matter of moving these [two lines](https://github.com/holoviz/panel/blob/main/panel/pane/markup.py#L370-L371) into the the [markdown-it renderer clause](https://github.com/holoviz/panel/blob/main/panel/pane/markup.py#L386).

**Comment by monodera** [comment]
Looks like a nice first contribution from me. I'll make a PR.
