### ISSUE TITLE
gapminder demo local bokeh server not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by Niko-La** [holoviz/panel#4025]
```
(default) nikola@nikola:~/Downloads/gapminder$ bokeh serve --show gapminder.ipynb
2022-10-18 23:51:08,734 Starting Bokeh server version 1.1.0 (running on Tornado 5.1.1)
2022-10-18 23:51:08,736 Bokeh app running at: http://localhost:5006/gapminder
2022-10-18 23:51:08,736 Starting Bokeh server with process id: 13328
Opening in existing browser session.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

2022-10-18 23:51:10,345 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f6fc76cea58>: module 'pandas.core' has no attribute 'index'
File "core.py", line 104, in sanitize_dataframe:
if isinstance(df.index, pd.core.index.MultiIndex): Traceback (most recent call last):
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/nikola/Downloads/gapminder/gapminder.ipynb", line 158, in <module>
    {
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 475, in servable
    self.server_doc()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 457, in server_doc
    model = self.get_root(doc)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 400, in get_root
    root = self._get_model(doc, comm=comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/param.py", line 575, in _get_model
    model = self._inner_layout._get_model(doc, root, parent, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 103, in _get_model
    json = self._to_json(self.object)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 66, in _to_json
    return obj.to_dict()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 398, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 84, in _prepare_data
    data = pipe(data, data_transformers.get())
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/data.py", line 12, in default_data_transformer
    return pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/data.py", line 129, in to_values
    data = sanitize_dataframe(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/core.py", line 104, in sanitize_dataframe
    if isinstance(df.index, pd.core.index.MultiIndex):
AttributeError: module 'pandas.core' has no attribute 'index'
 
2022-10-18 23:51:10,355 200 GET /gapminder (::1) 1476.28ms
2022-10-18 23:51:10,482 101 GET /gapminder/ws?bokeh-protocol-version=1.0&bokeh-session-id=0lipg831xBDPry9CLwV8YenD0cO2XABkKC3pGPSkUIpA (::1) 0.49ms
2022-10-18 23:51:10,482 WebSocket connection opened
2022-10-18 23:51:10,482 ServerConnection created
2022-10-18 23:51:10,508 404 GET /favicon.ico (::1) 0.40ms
/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

2022-10-18 23:52:08,004 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f6fc76cea58>: module 'pandas.core' has no attribute 'index'
File "core.py", line 104, in sanitize_dataframe:
if isinstance(df.index, pd.core.index.MultiIndex): Traceback (most recent call last):
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/nikola/Downloads/gapminder/gapminder.ipynb", line 158, in <module>
    {
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 475, in servable
    self.server_doc()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 457, in server_doc
    model = self.get_root(doc)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 400, in get_root
    root = self._get_model(doc, comm=comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/param.py", line 575, in _get_model
    model = self._inner_layout._get_model(doc, root, parent, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 103, in _get_model
    json = self._to_json(self.object)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 66, in _to_json
    return obj.to_dict()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 398, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 84, in _prepare_data
    data = pipe(data, data_transformers.get())
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/data.py", line 12, in default_data_transformer
    return pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/data.py", line 129, in to_values
    data = sanitize_dataframe(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/core.py", line 104, in sanitize_dataframe
    if isinstance(df.index, pd.core.index.MultiIndex):
AttributeError: module 'pandas.core' has no attribute 'index'
 
2022-10-18 23:52:08,006 200 GET /gapminder (::1) 390.46ms
2022-10-18 23:52:08,142 101 GET /gapminder/ws?bokeh-protocol-version=1.0&bokeh-session-id=t4sSteINRtcShCbJyWFzcu3gQmXFJyz0Mo8oh9FA7RBd (::1) 0.44ms
2022-10-18 23:52:08,142 WebSocket connection opened
2022-10-18 23:52:08,142 ServerConnection created
2022-10-18 23:53:44,146 WebSocket connection closed: code=1001, reason=None
2022-10-18 23:54:24,513 101 GET /gapminder/ws?bokeh-protocol-version=1.0&bokeh-session-id=hLTjMGg52v9nPJpYQbmwqhuQJSzvP8YdlKJDJ8QPnwC8 (::1) 0.54ms
2022-10-18 23:54:24,513 WebSocket connection opened
/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

2022-10-18 23:54:24,845 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f6fc76cea58>: module 'pandas.core' has no attribute 'index'
File "core.py", line 104, in sanitize_dataframe:
if isinstance(df.index, pd.core.index.MultiIndex): Traceback (most recent call last):
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/nikola/Downloads/gapminder/gapminder.ipynb", line 158, in <module>
    {
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 475, in servable
    self.server_doc()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 457, in server_doc
    model = self.get_root(doc)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 400, in get_root
    root = self._get_model(doc, comm=comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/param.py", line 575, in _get_model
    model = self._inner_layout._get_model(doc, root, parent, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 103, in _get_model
    json = self._to_json(self.object)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 66, in _to_json
    return obj.to_dict()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 398, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 84, in _prepare_data
    data = pipe(data, data_transformers.get())
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/data.py", line 12, in default_data_transformer
    return pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/data.py", line 129, in to_values
    data = sanitize_dataframe(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/core.py", line 104, in sanitize_dataframe
    if isinstance(df.index, pd.core.index.MultiIndex):
AttributeError: module 'pandas.core' has no attribute 'index'
 
2022-10-18 23:54:24,845 ServerConnection created
2022-10-18 23:54:24,932 WebSocket connection closed: code=1001, reason=None
2022-10-18 23:54:26,393 101 GET /gapminder/ws?bokeh-protocol-version=1.0&bokeh-session-id=t4sSteINRtcShCbJyWFzcu3gQmXFJyz0Mo8oh9FA7RBd (::1) 0.46ms
2022-10-18 23:54:26,393 WebSocket connection opened
/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/holoviews/plotting/util.py:674: MatplotlibDeprecationWarning:

The global colormaps dictionary is no longer considered public API.

2022-10-18 23:54:26,702 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f6fc76cea58>: module 'pandas.core' has no attribute 'index'
File "core.py", line 104, in sanitize_dataframe:
if isinstance(df.index, pd.core.index.MultiIndex): Traceback (most recent call last):
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/nikola/Downloads/gapminder/gapminder.ipynb", line 158, in <module>
    {
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 475, in servable
    self.server_doc()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 457, in server_doc
    model = self.get_root(doc)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/viewable.py", line 400, in get_root
    root = self._get_model(doc, comm=comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/param.py", line 575, in _get_model
    model = self._inner_layout._get_model(doc, root, parent, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 103, in _get_model
    json = self._to_json(self.object)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/panel/pane/vega.py", line 66, in _to_json
    return obj.to_dict()
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 398, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 84, in _prepare_data
    data = pipe(data, data_transformers.get())
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/vegalite/data.py", line 12, in default_data_transformer
    return pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/data.py", line 129, in to_values
    data = sanitize_dataframe(data)
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/altair/utils/core.py", line 104, in sanitize_dataframe
    if isinstance(df.index, pd.core.index.MultiIndex):
AttributeError: module 'pandas.core' has no attribute 'index'
 
2022-10-18 23:54:26,702 ServerConnection created
2022-10-18 23:54:27,368 WebSocket connection closed: code=1001, reason=None

```

**Comment by philippjfr** [comment]
This looks like a bug in altair. I suspect either pandas or altair dropped python 3.6 support so their APIs are drifting out of sync. Also note that Panel officially does not support Python 3.6 either so I'll close.

**Comment by Niko-La** [comment]
```
base) nikola@nikola:~/Downloads/gapminder$ panel serve --show gapminder.ipynb
2022-10-19 12:17:13,108 Starting Bokeh server version 2.4.3 (running on Tornado 6.1)
2022-10-19 12:17:13,108 User authentication hooks NOT provided (default user enabled)
2022-10-19 12:17:13,109 Bokeh app running at: http://localhost:5006/gapminder
2022-10-19 12:17:13,109 Starting Bokeh server with process id: 7282
2022-10-19 12:17:18,132 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7f1c065e15e0>: name 'get_ipython' is not defined
File 'gapminder.ipynb', line 11, in <module>:
"cell_type": "markdown", Traceback (most recent call last):
  File "/home/nikola/anaconda3/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/home/nikola/Downloads/gapminder/gapminder.ipynb", line 11, in <module>
    "cell_type": "markdown",
NameError: name 'get_ipython' is not defined
 
2022-10-19 12:17:18,309 WebSocket connection opened
2022-10-19 12:17:18,310 ServerConnection created
2022-10-19 12:17:18,340 404 GET /favicon.ico (::1) 0.39ms

```

this is on python 3.9


was broken even when running 
`anaconda-pythob run`

**Comment by philippjfr** [comment]
Thanks, really appreciate the detailed reports.

**Comment by Niko-La** [comment]
no problem @philippjfr 

yup getting the same issue with anaconda-project run, which is supposed to be repoducible.  

```
  * anaconda-project.yml: Unknown field name 'maintainers'

2022-10-19 12:23:35,113 Starting Bokeh server version 1.1.0 (running on Tornado 5.1.1)
2022-10-19 12:23:35,114 Bokeh app running at: http://localhost:5006/gapminder
2022-10-19 12:23:35,114 Starting Bokeh server with process id: 11367
2022-10-19 12:23:41,632 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7faee671c630>: name 'get_ipython' is not defined
File "gapminder.ipynb", line 11, in <module>:
"cell_type": "markdown", Traceback (most recent call last):
  File "/home/nikola/Downloads/gapminder/envs/default/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/nikola/Downloads/gapminder/gapminder.ipynb", line 11, in <module>
    "cell_type": "markdown",
NameError: name 'get_ipython' is not defined
 
2022-10-19 12:23:41,641 200 GET /gapminder (::1) 13.92ms
2022-10-19 12:23:41,713 101 GET /gapminder/ws?bokeh-protocol-version=1.0&bokeh-session-id=6tW6zXvYvLDwrJUG2QyrGJpiYUc8uETWk3wR2czfNO8l (::1) 0.48ms
2022-10-19 12:23:41,713 WebSocket connection opened
2022-10-19 12:23:41,713 ServerConnection created

```
