### PR TITLE
Annotate pn.io.cache decorator

### PR DESCRIPTION
**Pull request by gandhis1**
Part of https://github.com/holoviz/panel/issues/7078

In the docs I see that [minimum Python version is 3.9](https://panel.holoviz.org/developer_guide/index.html#create-a-development-environment), however in the `pyproject.toml` it states `requires-python = ">=3.10"`. Importing `ParamSpec` from `typing` instead of `typing_extensions` requires 3.10. This PR assumes the latter is correct and that `typing_extensions` is not required.

@MarcSkovMadsen

### CODE REVIEW

**Comment by gandhis1** [comment]
It looks like the `main` build was failing until it was fixed a few hours ago, so I will rebase this...

```
=========================== short test summary info ============================
FAILED panel/tests/ui/widgets/test_tabulator.py::test_tabulator_header_filter_no_horizontal_rescroll[remote] - AssertionError: assert {'height': 20...: 264, 'y': 9} == {'height': 20...: 714, 'y': 9}
  Omitting 3 identical items, use -vv to show
  Differing items:
  {'x': 264} != {'x': 714}
  Full diff:
  - {'height': 20, 'width': 91, 'x': 714, 'y': 9}
  ?                                  ^^
  + {'height': 20, 'width': 91, 'x': 264, 'y': 9}
  ?                                  ^^
== 1 failed, 562 passed, 10 skipped, 28 xfailed, 4 rerun in 770.47s (0:12:50) ==
```

**Comment by MarcSkovMadsen** [comment]
I'm wondering whats the best way to check this via `mypy`.

I tried `mypy --follow-imports=skip panel/io/cache.py` but it errors.

```bash
$ mypy --follow-imports=skip panel/io/cache.py
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
             ^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 103, in main
  File "mypy/main.py", line 187, in run_build
  File "mypy/build.py", line 193, in build
  File "mypy/build.py", line 268, in _build
  File "mypy/build.py", line 2950, in dispatch
  File "mypy/build.py", line 3348, in process_graph
  File "mypy/build.py", line 3475, in process_stale_scc
  File "mypy/build.py", line 2507, in write_cache
  File "mypy/build.py", line 1568, in write_cache
  File "mypy/nodes.py", line 390, in serialize
  File "mypy/nodes.py", line 4012, in serialize
  File "mypy/nodes.py", line 3949, in serialize
  File "mypy/nodes.py", line 3374, in serialize
  File "mypy/types.py", line 671, in serialize
  File "mypy/types.py", line 2428, in serialize
  File "mypy/types.py", line 1451, in serialize
  File "mypy/types.py", line 671, in serialize
  File "mypy/types.py", line 3093, in serialize
AssertionError: Internal error: unresolved placeholder type None
```

Then I tried `mypy panel/io/cache.py` which seems to work better.

```bash
$ mypy panel/io/cache.py
panel/io/cache.py:24: error: Skipping analyzing "param": module is installed, but missing library stubs or py.typed marker  [import-untyped]
panel/io/cache.py:26: error: Skipping analyzing "param.parameterized": module is installed, but missing library stubs or py.typed marker  [import-untyped]
panel/io/cache.py:26: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
panel/io/cache.py:38: error: Need type annotation for "_HASH_MAP" (hint: "_HASH_MAP: dict[<type>, <type>] = ...")  [var-annotated]
panel/io/cache.py:40: error: Need type annotation for "_HASH_STACKS"  [var-annotated]
panel/io/cache.py:110: error: Library stubs not installed for "pandas"  [import-untyped]
panel/io/cache.py:110: note: Hint: "python3 -m pip install pandas-stubs"
panel/io/cache.py:110: note: (or run "mypy --install-types" to install all missing stub packages)
panel/io/cache.py:177: error: Incompatible types in assignment (expression has type "bytes", target has type "Callable[[Any], Any]")  [assignment]
panel/io/cache.py:389: error: Incompatible return value type (got "Callable[[Any], Callable[[Callable[P, R]], Callable[P, R]]]", expected "Callable[P, R@cache] | Callable[[Callable[P, R@cache]], Callable[P, R@cache]]")  [return-value]
panel/io/cache.py:436: error: Cannot find implementation or library stub for module named "diskcache"  [import-not-found]
panel/io/cache.py:462: error: Incompatible types in "await" (actual type "R", expected type "Awaitable[Any]")  [misc]
panel/io/cache.py:493: error: "_Wrapped[P, R, P, Coroutine[Any, Any, R]]" has no attribute "clear"  [attr-defined]
panel/io/cache.py:505: error: Incompatible return value type (got "_Wrapped[P, R, P, Coroutine[Any, Any, R]]", expected "Callable[P, R] | Callable[[Callable[P, R]], Callable[P, R]]")  [return-value]
Found 11 errors in 1 file (checked 1 source file)
```

**Comment by MarcSkovMadsen** [comment]
I've tried to configure `mypy` in https://github.com/holoviz/panel/pull/7081. Could you do a review of that one @gandhis1? Thanks.

**Comment by MarcSkovMadsen** [comment]
I can see that @hoxbro updated to Python 3.10 in #6883. This PR has not yet been released. I.e. the upgrade to Python 3.10 for users will happen when 1.5.0 is released.

File: panel/io/cache.py [hunk 1]
```diff
@@ -305,11 +308,46 @@ def compute_hash(func, hash_funcs, args, kwargs):
         _HASH_MAP[key] = hash_value
     return hash_value
 
+P = ParamSpec("P")
+R = TypeVar("R")
+T = TypeVar("T")
+
+@overload
```
Comment (MarcSkovMadsen) [inline panel/io/cache.py:315]: After merging this PR with 7081 the errors I see for the `panel/io/cache.py` file are

```bash
panel/io/cache.py:38: error: Need type annotation for "_HASH_MAP" (hint: "_HASH_MAP: dict[<type>, <type>] = ...")  [var-annotated]
panel/io/cache.py:40: error: Need type annotation for "_HASH_STACKS"  [var-annotated]
panel/io/cache.py:177: error: Incompatible types in assignment (expression has type "bytes", target has type "Callable[[Any], Any]")  [assignment]
panel/io/cache.py:389: error: Incompatible return value type (got "Callable[[Any], Callable[[Callable[P, R]], Callable[P, R]]]", expected "Callable[P, R@cache] | Callable[[Callable[P, R@cache]], Callable[P, R@cache]]")  [return-value]
panel/io/cache.py:462: error: Incompatible types in "await" (actual type "R", expected type "Awaitable[Any]")  [misc]
panel/io/cache.py:493: error: "_Wrapped[P, R, P, Coroutine[Any, Any, R]]" has no attribute "clear"  [attr-defined]
panel/io/cache.py:505: error: Incompatible return value type (got "_Wrapped[P, R, P, Coroutine[Any, Any, R]]", expected "Callable[P, R] | Callable[[Callable[P, R]], Callable[P, R]]")  [return-value]
```

Thus I see some issue in line 389 after the cache type annoation is introduced. I don't see issues introduced in other files.

File: panel/io/cache.py [hunk 2]
```diff
@@ -305,11 +308,46 @@ def compute_hash(func, hash_funcs, args, kwargs):
...
+def cache(
+    func: Literal[None] = ...,
+    hash_funcs: dict[type[Any], Callable[[Any], bytes]] | None = ...,
+    max_items: int | None = ...,
+    policy: Literal['FIFO', 'LRU', 'LFU'] = ...,
+    ttl: float | None = ...,
+    to_disk: bool = ...,
+    cache_path: str = ...,
+    per_session: bool = ...,
+) -> Callable[[Callable[P, R]], Callable[P, R]]:
```
Comment (MarcSkovMadsen) [inline panel/io/cache.py:325]: I'm not an expert on type check, so I would like to learn why this is needed. Can you please explain?

File: panel/io/cache.py [hunk 3]
```diff
@@ -305,11 +308,46 @@ def compute_hash(func, hash_funcs, args, kwargs):
...
-    func=None, hash_funcs=None, max_items=None, policy='LRU',
-    ttl=None, to_disk=False, cache_path='./cache', per_session=False
-):
+    func: Callable[P, R] | None = None,
+    hash_funcs: dict[type[Any], Callable[[Any], bytes]] | None = None,
+    max_items: int | None = None,
+    policy: Literal['FIFO', 'LRU', 'LFU'] = 'LRU',
+    ttl: float | None = None,
+    to_disk: bool = False,
+    cache_path: str = './cache',
```
Comment (MarcSkovMadsen) [inline panel/io/cache.py:348]: I see `cache_path` is documented as `cache_dir` in the docstring. Please consider fixing. Thanks.

Comment (MarcSkovMadsen) [inline panel/io/cache.py:348]: As far as I can see `cache_path` is used as input to `os.path.join`. Thus I believe that it could also be a `pathlib.Path` type and that the type annotation should be updated to this?

File: panel/io/cache.py [hunk 4]
```diff
@@ -414,7 +452,7 @@ def hash_func(*args, **kwargs):
 
     if iscoroutinefunction(func):
         @functools.wraps(func)
-        async def wrapped_func(*args, **kwargs):
+        async def wrapped_func(*args: P.args, **kwargs: P.kwargs) -> R:
```
Comment (MarcSkovMadsen) [inline panel/io/cache.py:455]: For me to learn. Can you explain what goes on here? Thanks.

**Comment by MarcSkovMadsen** [comment]
Note to my self. I should consider contributing an example to the docstring and maybe a link to reference docs to align with other docstrings.

File: panel/io/cache.py (hunk 3 above)
Comment (hoxbro) [reply panel/io/cache.py:348]: I _think_ `str | os.PathLike` is right.

File: panel/io/cache.py [hunk 5]
```diff
@@ -305,11 +308,46 @@ def compute_hash(func, hash_funcs, args, kwargs):
         _HASH_MAP[key] = hash_value
     return hash_value
 
+P = ParamSpec("P")
+R = TypeVar("R")
+T = TypeVar("T")
```
Comment (hoxbro) [inline panel/io/cache.py:313]: Maybe add these below  the imports behind `TYPE_CHECKING`

**Comment by hoxbro** [comment]
> I can see that @hoxbro updated to Python 3.10 in https://github.com/holoviz/panel/pull/6883.

Yep, Bokeh 3.5 dropped Python 3.9 support. So we dropped it, too, as we are hard pinned to 3.5.

File: panel/io/cache.py (hunk 1 above)
Comment (hoxbro) [reply panel/io/cache.py:315]: Maybe a relevant youtube video:  https://www.youtube.com/watch?v=_QXlbwRmqgI

File: panel/io/cache.py (hunk 2 above)
Comment (gandhis1) [reply panel/io/cache.py:325]: `cache` has situational behavior depending on the arguments, it can either be a first-order decorator or a second-order decorator.

If you use it as `@pn.cache(ttl=60)`, then you are effectively using as a function that returns a decorator (`pn.cache(ttl=60)(my_func)`) or a second-order decorator. That is one of the overloads.

If you use it as `@st.cache`. you are using it as a first-order decorator (`pn.cache(my_func)`). That is the second overload.

The overloads are vitally important because for user code the most important thing is that, regardless of how `cache` is used, it needs to always return a final function with a type signature that looks the same as the user's original function. This should achieve that.

File: panel/io/cache.py (hunk 4 above)
Comment (gandhis1) [reply panel/io/cache.py:455]: `ParamSpec` `P` represents the type signatures of the `func` that was passed in. Since `func` was annotated as `Callable[P, R]`, this is just saying that `wrapped_func` has the same signature as `func`. It doesn't really make a practical difference here, but for instance, something you could do is add an extra positional or keyword argument to `wrapped_func`, and that would get validated in subsequent calls.

**Comment by gandhis1** [comment]
I will make the requested changes and address the Mypy errors later today.

File: panel/io/cache.py (hunk 1 above)
Comment (gandhis1) [reply panel/io/cache.py:317]: The line 389 issue I fixed by converting the `lambda` into a regular `def`, which supports annotations.

I took an initial look at fixing the others as well:

- Added an annotation for `_HASH_MAP`
- `_HASH_STACKS` does not even appear to be used anywhere, so I couldn't figure out what it was supposed to be annotated as. `_STACK` is likewise not used anywhere. Can these be deleted?
- The line 177 error sure looks like a bug? How can a hash function be a bytes constant (see snippet below)? Those are not callable and `hash_func` is used as a callable.
```
for name in _FFI_TYPE_NAMES:
    _hash_funcs[name] = b'0'
```
- The line 493 error I ignored for now, as it is assigned an arbitrary attribute `clear` on a function. We might be able to define a more precise return type that annotates the `clear` as well but that is probably overkill.
- The remaining `async` / `await` errors I partially fixed by adding an `Awaitable` variant, however I had to add a `type: ignore` for one of them because `iscoroutinefunction` does not implement a `TypeGuard`, which it would need to to avoid the ignore. (note that `inspect.iscoroutinefunction` does implement this in `typeshed`).

**Review by MarcSkovMadsen — APPROVED** [review]
With the (limited) knowledge of typing I have, I can approve.

I believe the remaining questions can should be answered by Philipp.

**Comment by hoxbro** [comment]
Having variables in `TYPE_CHECKING` makes them private. I prefer having them there, as it also makes it easier to read, but I'm not sure what the "standard" is.

**Comment by gandhis1** [comment]
> Having variables in `TYPE_CHECKING` makes them private. I prefer having them there, as it also makes it easier to read, but I'm not sure what the "standard" is.

I restored this - the errors I previously encountered when doing this was because I was missing `from __future__ import annotations`.

**Comment by gandhis1** [comment]
The tests keep on failing in places I am unfamiliar with. Do these test failures actually have anything to do with this PR?

**Comment by philippjfr** [comment]
Some tests seem to be a little flakey will look at those again soon, but you're good to go here!
