### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'add_future

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4724]
I'm on panel== 1.0.0rc1.

I'm trying to make an updated gif for the `--autoreload` feature to include in the docs. I wanted to add a bit of streaming. But it fails.

```python
import numpy as np

import panel as pn

pn.extension()

data = {'x': np.arange(50), 'y': np.random.randn(50).cumsum()}
section3 = pn.indicators.Trend(
    title='Indicator', data=data, height=200, sizing_mode="stretch_width",
)
def stream_data():
    section3.stream({'x': [section3.data['x'][-1]+1], 'y': [section3.data['y'][-1]+np.random.randn()]}, rollover=50)

pn.state.add_periodic_callback(stream_data, period=1000, count=100)

section3.servable()
```

```bash
$ panel serve script2.py --autoreload
ERROR: 'NoneType' object has no attribute 'add_future'
```

If I remove the `--autoreload` flag it works or if I remove the `pn.state.add_periodic_callback` line it works.

**Comment by Hoxbro** [comment]
This regression seems to have been added in #4658
